import { randomBytes } from "node:crypto";
import { access, readdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { E2eRequest, E2eResponse } from "../../src/e2e/protocol";
import { E2E_CHANNEL_READY_MARKER } from "../../src/e2e/transportFs";

const DEFAULT_READINESS_TIMEOUT_MS = 30_000;
const DEFAULT_RESPONSE_TIMEOUT_MS = 30_000;
const DEFAULT_POLL_INTERVAL_MS = 50;

type WithoutNonce<T> = T extends unknown ? Omit<T, "nonce"> : never;

/** A request body whose correlation nonce is generated by the client. */
export type E2eRequestInput = WithoutNonce<E2eRequest>;

/** Timeouts and polling cadence used by {@link E2eControlChannelClient}. */
export interface E2eControlChannelClientOptions {
    /** Maximum time to wait for the extension's readiness marker before the first request. */
    readonly readinessTimeoutMs?: number;
    /** Maximum time to wait for each correlated response file. */
    readonly responseTimeoutMs?: number;
    /** Delay between readiness and response filesystem polls. */
    readonly pollIntervalMs?: number;
}

/**
 * Waits until the extension publishes its readiness marker or the bounded timeout expires.
 *
 * The marker is deliberately checked before any request file is created, so an activated
 * watcher cannot miss the request during its startup drain.
 */
async function waitForE2eChannelReady(
    channelDir: string,
    timeoutMs = DEFAULT_READINESS_TIMEOUT_MS,
    pollIntervalMs = DEFAULT_POLL_INTERVAL_MS,
): Promise<void> {
    const markerPath = join(channelDir, E2E_CHANNEL_READY_MARKER);
    const deadline = Date.now() + timeoutMs;

    while (true) {
        try {
            await access(markerPath);
            return;
        } catch {
            const remainingMs = deadline - Date.now();
            if (remainingMs <= 0) {
                throw new Error(`E2E control channel never became ready within ${timeoutMs}ms`);
            }
            await sleep(Math.min(pollIntervalMs, remainingMs));
        }
    }
}

/**
 * Publishes one request with a same-directory temp-file-plus-rename sequence. A watcher can
 * therefore observe either no request or the complete JSON document, never a partial write.
 */
export async function writeE2eRequestAtomic(
    channelDir: string,
    request: E2eRequest,
): Promise<void> {
    const finalPath = join(channelDir, `${request.nonce}.request.json`);
    const tempPath = join(
        channelDir,
        `.${request.nonce}.${randomBytes(8).toString("hex")}.request.tmp`,
    );
    let published = false;

    try {
        await writeFile(tempPath, JSON.stringify(request), "utf8");
        await rename(tempPath, finalPath);
        published = true;
    } finally {
        if (!published) {
            await unlink(tempPath).catch(() => undefined);
        }
    }
}

/**
 * Polls for one correlated response, ignoring the expected missing-file and transient invalid
 * JSON states until a valid JSON envelope is available or the response timeout expires.
 */
async function waitForE2eResponse(
    channelDir: string,
    nonce: string,
    timeoutMs = DEFAULT_RESPONSE_TIMEOUT_MS,
    pollIntervalMs = DEFAULT_POLL_INTERVAL_MS,
): Promise<E2eResponse> {
    const responsePath = join(channelDir, `${nonce}.response.json`);
    const deadline = Date.now() + timeoutMs;

    while (true) {
        try {
            const raw = await readFile(responsePath, "utf8");
            return JSON.parse(raw) as E2eResponse;
        } catch {
            const remainingMs = deadline - Date.now();
            if (remainingMs <= 0) {
                // The bare timeout cannot distinguish the failure modes, and they have different
                // fixes. A surviving `<nonce>.request.json` means the request was never answered:
                // either the extension never observed it, or delivery keeps failing and
                // reconciliation is still retrying it. A directory holding neither file instead
                // means the channel was torn down underneath the request. Since the extension
                // writes the response before removing the request, "consumed but unanswered" is
                // not a state this transport can reach.
                throw new Error(
                    `E2E control channel response for nonce ${nonce} did not arrive within ${timeoutMs}ms. ` +
                        `Channel directory contained: ${await describeChannelDir(channelDir)}`,
                );
            }
            await sleep(Math.min(pollIntervalMs, remainingMs));
        }
    }
}

/**
 * Generates a nonce composed only of characters accepted by the extension transport filename
 * validator. Hex encoding is restricted to the transport's alphanumeric character set.
 */
function generateE2eNonce(): string {
    return randomBytes(16).toString("hex");
}

/**
 * Lists the channel directory for a timeout message. Never throws: this runs only on a path that
 * is already failing, and an unreadable directory is itself the answer worth reporting.
 */
async function describeChannelDir(channelDir: string): Promise<string> {
    try {
        const entries = await readdir(channelDir);
        return entries.length === 0 ? "<empty>" : entries.sort().join(", ");
    } catch (error) {
        return `<unreadable: ${String(error)}>`;
    }
}

/** Resolves after the requested polling interval without blocking the Playwright process. */
function sleep(delayMs: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, delayMs));
}

/**
 * Sends correlated requests to the extension-side E2E control channel over its file transport.
 * The readiness marker is awaited once per client, before the first request is published.
 */
export class E2eControlChannelClient {
    private ready = false;

    /** Creates a client rooted at one fixture-owned control-channel directory. */
    public constructor(
        private readonly channelDir: string,
        private readonly options: E2eControlChannelClientOptions = {},
    ) {}

    /** Publishes a nonce-bound request and returns its parsed correlated response. */
    public async request(payload: E2eRequestInput): Promise<E2eResponse> {
        if (!this.ready) {
            await waitForE2eChannelReady(
                this.channelDir,
                this.options.readinessTimeoutMs,
                this.options.pollIntervalMs,
            );
            this.ready = true;
        }

        const request = { ...payload, nonce: generateE2eNonce() } as E2eRequest;
        await writeE2eRequestAtomic(this.channelDir, request);
        return waitForE2eResponse(
            this.channelDir,
            request.nonce,
            this.options.responseTimeoutMs,
            this.options.pollIntervalMs,
        );
    }
}
