import { describe, expect, it, vi } from "vitest";

vi.mock("vscode", () => ({
    l10n: { t: (message: string) => message },
    commands: { executeCommand: vi.fn(async () => undefined) },
    window: { showWarningMessage: vi.fn(), showInformationMessage: vi.fn() },
}));

import type { OutboundMessage } from "../../../src/webviews/protocol/commitPanelMessages";
import {
    assertShelfChangeId,
    assertShelfGeneration,
    assertShelfId,
    assertShelfName,
    assertShelfToken,
} from "../../../src/views/messageValidation";
import { executeShelfMutationRequest } from "../../../src/views/commitPanelActions";
import { RepositoryLockBusyError } from "../../../src/git/repositoryLock";
import {
    ShelfRecoveryFullError,
    ShelfStaleCatalogError,
    ShelfStaleShelfError,
} from "../../../src/services/shelfService";

const shelfSaveMessage = {
    type: "shelveSave",
    requestId: "request-1",
    name: "before rebase",
    paths: ["src/a.ts"],
    silent: false,
    keepLocal: false,
    idempotencyToken: "save-1",
    expectedCatalogGeneration: 4,
} satisfies OutboundMessage;

describe("shelf webview validation", () => {
    it.each([undefined, null, 1, true, "", "has space", "x".repeat(129)])(
        "rejects invalid shelf IDs: %j",
        (value) => {
            expect(() => assertShelfId(value, "shelfId")).toThrow();
        },
    );

    it.each([undefined, null, 1, true, "", "bad/id", "x".repeat(129)])(
        "rejects invalid change IDs: %j",
        (value) => {
            expect(() => assertShelfChangeId(value, "changeId")).toThrow();
        },
    );

    it.each([undefined, null, "1", true, -1, 1.2, Number.NaN, Number.POSITIVE_INFINITY])(
        "rejects invalid generations: %j",
        (value) => {
            expect(() => assertShelfGeneration(value, "expectedGeneration")).toThrow();
        },
    );

    it.each([undefined, null, 1, true, "", "x".repeat(257)])(
        "rejects invalid idempotency tokens: %j",
        (value) => {
            expect(() => assertShelfToken(value, "idempotencyToken")).toThrow();
        },
    );

    it.each([undefined, null, 1, true, "", "   ", "bad\0name", "x".repeat(256)])(
        "rejects invalid shelf names without rewriting them: %j",
        (value) => {
            expect(() => assertShelfName(value, "name")).toThrow();
        },
    );

    it("keeps valid shelf names verbatim", () => {
        expect(assertShelfName("  exact shelf name  ", "name")).toBe("  exact shelf name  ");
    });

    it("rejects a client-supplied shelf ID during shelf creation", async () => {
        const postCompleted = vi.fn();
        await expect(
            executeShelfMutationRequest(
                {
                    shelfService: { shelve: vi.fn() },
                    refreshData: vi.fn(async () => undefined),
                    fireWorkingTreeChanged: vi.fn(),
                } as never,
                { ...shelfSaveMessage, shelfId: "client-chosen" },
                postCompleted,
            ),
        ).rejects.toThrow("generated by the host");
        expect(postCompleted).toHaveBeenCalledWith(
            expect.objectContaining({ status: "error", requestId: "request-1" }),
        );
    });
});

describe("executeShelfMutationRequest", () => {
    it("includes the verbatim mutation failure text in its completion", async () => {
        const postCompleted = vi.fn();
        const error = new Error("Name conflicts with a locked shelf.");
        await expect(
            executeShelfMutationRequest(
                {
                    shelfService: { shelve: vi.fn(async () => Promise.reject(error)) },
                    refreshData: vi.fn(async () => undefined),
                    fireWorkingTreeChanged: vi.fn(),
                } as never,
                shelfSaveMessage,
                postCompleted,
            ),
        ).rejects.toBe(error);
        expect(postCompleted).toHaveBeenCalledWith(
            expect.objectContaining({ message: "Name conflicts with a locked shelf." }),
        );
    });

    it("completes a cancelled host export picker without calling the service", async () => {
        const postCompleted = vi.fn();
        const exportPatch = vi.fn();
        await executeShelfMutationRequest(
            {
                shelfService: { exportPatch },
                refreshData: vi.fn(async () => undefined),
                fireWorkingTreeChanged: vi.fn(),
                selectExportDestination: vi.fn(async () => undefined),
            } as never,
            {
                type: "shelfExportPatch",
                requestId: "request-export",
                shelfId: "shelf-1",
                expectedGeneration: 1,
            },
            postCompleted,
        );
        expect(exportPatch).not.toHaveBeenCalled();
        expect(postCompleted).toHaveBeenCalledWith(
            expect.objectContaining({ requestId: "request-export", status: "ok", entries: [] }),
        );
    });

    it("imports only host-picked patch paths and treats picker cancellation as a successful no-op", async () => {
        const importPatch = vi.fn(async () => ({ status: "ok" as const, entries: [], shelfId: "imported" }));
        const postCompleted = vi.fn();
        const message = {
            type: "shelfImportPatch",
            requestId: "request-import",
            idempotencyToken: "import-token",
            expectedCatalogGeneration: 4,
        };
        await executeShelfMutationRequest(
            {
                shelfService: { importPatch, listShelves: vi.fn(async () => ({ shelfIds: [], corruptShelfIds: [], shelves: [], catalogGeneration: 5 })) },
                refreshData: vi.fn(async () => undefined),
                fireWorkingTreeChanged: vi.fn(),
                selectImportSources: vi.fn(async () => ["/host/first.patch", "/host/second.diff"]),
            } as never,
            message,
            postCompleted,
        );
        expect(importPatch).toHaveBeenCalledWith({
            fileUris: ["/host/first.patch", "/host/second.diff"],
            idempotencyToken: "import-token",
            expectedCatalogGeneration: 4,
        });

        await executeShelfMutationRequest(
            {
                shelfService: { importPatch },
                refreshData: vi.fn(async () => undefined),
                fireWorkingTreeChanged: vi.fn(),
                selectImportSources: vi.fn(async () => undefined),
            } as never,
            message,
            postCompleted,
        );
        expect(importPatch).toHaveBeenCalledOnce();
        expect(postCompleted).toHaveBeenLastCalledWith(
            expect.objectContaining({ requestId: "request-import", status: "ok", entries: [] }),
        );
    });

    it("posts typed completion with every per-entry kind after a successful mutation", async () => {
        const shelfService = {
            shelve: vi.fn(async () => ({
                status: "partial" as const,
                shelfId: "shelf-1",
                newGeneration: 3,
                entries: [
                    { kind: "applied" as const, changeId: "change-1" },
                    { kind: "conflicted" as const, changeId: "change-2" },
                    { kind: "retained" as const, changeId: "change-3", reason: "retained" },
                    { kind: "flattenedResidue" as const, changeId: "change-4" },
                    { kind: "refused" as const, changeId: "change-5", reason: "refused" },
                    {
                        kind: "structuralPending" as const,
                        changeId: "change-6",
                        reason: "structural",
                    },
                ],
            })),
            listShelves: vi.fn(async () => ({ shelfIds: [], corruptShelfIds: [], shelves: [], catalogGeneration: 5 })),
        };
        const refreshData = vi.fn(async () => undefined);
        const fireWorkingTreeChanged = vi.fn();
        const postCompleted = vi.fn();

        await executeShelfMutationRequest(
            { shelfService, refreshData, fireWorkingTreeChanged },
            shelfSaveMessage,
            postCompleted,
        );

        expect(shelfService.shelve).toHaveBeenCalledWith({
            name: "before rebase",
            paths: ["src/a.ts"],
            silent: false,
            keepLocal: false,
            idempotencyToken: "save-1",
            expectedCatalogGeneration: 4,
        });
        expect(postCompleted).toHaveBeenCalledWith({
            type: "shelfMutationCompleted",
            requestId: "request-1",
            status: "partial",
            shelfId: "shelf-1",
            newGeneration: 3,
            newCatalogGeneration: 5,
            entries: expect.arrayContaining([
                expect.objectContaining({ kind: "applied", changeId: "change-1" }),
                expect.objectContaining({ kind: "conflicted", changeId: "change-2" }),
                expect.objectContaining({ kind: "retained", changeId: "change-3" }),
                expect.objectContaining({ kind: "flattenedResidue", changeId: "change-4" }),
                expect.objectContaining({ kind: "refused", changeId: "change-5" }),
                expect.objectContaining({ kind: "structuralPending", changeId: "change-6" }),
            ]),
        });
        expect(refreshData).toHaveBeenCalledOnce();
        expect(fireWorkingTreeChanged).toHaveBeenCalledOnce();
    });

    it.each([
        [new RepositoryLockBusyError(), "busy"],
        [new ShelfStaleShelfError(2, 3), "staleShelf"],
        [new ShelfStaleCatalogError(2, 3), "staleCatalog"],
        [new ShelfRecoveryFullError(), "recoveryFull"],
    ] as const)("maps %s to the typed %s completion", async (error, status) => {
        const postCompleted = vi.fn();
        await expect(
            executeShelfMutationRequest(
                {
                    shelfService: { shelve: vi.fn(async () => Promise.reject(error)) },
                    refreshData: vi.fn(async () => undefined),
                    fireWorkingTreeChanged: vi.fn(),
                } as never,
                shelfSaveMessage,
                postCompleted,
            ),
        ).rejects.toBe(error);
        expect(postCompleted).toHaveBeenCalledWith(
            expect.objectContaining({ requestId: "request-1", status, entries: [] }),
        );
    });
});
